In [1]:
import numpy as np
from matplotlib import pylab as plt

In [2]:
x = np.linspace(-10, 10, 50)
x

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [3]:
y = 2.3 * x - 3
y

array([-26.        , -25.06122449, -24.12244898, -23.18367347,
       -22.24489796, -21.30612245, -20.36734694, -19.42857143,
       -18.48979592, -17.55102041, -16.6122449 , -15.67346939,
       -14.73469388, -13.79591837, -12.85714286, -11.91836735,
       -10.97959184, -10.04081633,  -9.10204082,  -8.16326531,
        -7.2244898 ,  -6.28571429,  -5.34693878,  -4.40816327,
        -3.46938776,  -2.53061224,  -1.59183673,  -0.65306122,
         0.28571429,   1.2244898 ,   2.16326531,   3.10204082,
         4.04081633,   4.97959184,   5.91836735,   6.85714286,
         7.79591837,   8.73469388,   9.67346939,  10.6122449 ,
        11.55102041,  12.48979592,  13.42857143,  14.36734694,
        15.30612245,  16.24489796,  17.18367347,  18.12244898,
        19.06122449,  20.        ])

In [7]:
a = 5.3
b = -5.1
delta = np.inf
eta = 0.0001
D = [(a, b)]

In [12]:
while delta > 0.0001:
    hy = a * x + b
    e = (y - hy)
    a = a + 2 * eta * (e * x).sum()
    b = b + 2 * eta * e.sum()
    D.append((a, b))
    delta = np.fabs(np.array(D[-1]) - np.array(D[-2])).mean()

In [13]:
D

[(5.3, -5.1),
 (4.259183673469387, -5.079),
 (3.5794668887963343, -5.05821),
 (3.1355702130914835, -5.0376278999999995),
 (2.845678506508724, -5.017251621),
 (2.6563614736383503, -4.99707910479),
 (2.532725860335249, -4.9771083137421),
 (2.4519842353209786, -4.957337230604679),
 (2.3992550108218635, -4.9377638582986325),
 (2.364819598904074, -4.9183862197156465),
 (2.342331166631232, -4.89920235751849),
 (2.327644843514274, -4.880210333943305),
 (2.3180537753562604, -4.861408230603872),
 (2.311790220640823, -4.842794148297833),
 (2.3076997359287006, -4.8243662068148545),
 (2.305028398973845, -4.806122544746706),
 (2.3032838523910826, -4.7880613192992385),
 (2.302144556663564, -4.770180706106246),
 (2.3014005268006947, -4.752478899045184),
 (2.3009146297473926, -4.7349541100547325),
 (2.300597309222787, -4.717604568954185),
 (2.3003900794924323, -4.700428523264643),
 (2.3002547457909763, -4.683424238031996),
 (2.3001663645981885, -4.666589995651677),
 (2.3001086462682045, -4.64992409569

In [1]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [2]:
ann = MLPClassifier().fit(X, y)
ann.predict(X)

c:\Users\viper\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])